name: model-wine-quality
on: [push] 
jobs:  
  run:    
    runs-on: [ubuntu-latest] 
    container: docker://dvcorg/cml-py3:latest 
    steps:
      - uses: actions/checkout@v2              
      - name: cml_run        
        env:          
          repo_token: ${{secrets.PAT}}
        run:
          echo "MODEL METRICS"
