name: model-wine-quality
on: [push] 
jobs:  
  run:    
    runs-on: [ubuntu-latest] 
    container:     
    steps:
      - uses: actions/checkout@v2              
      - name: cml_run        
        env:          
          repo_token: ${{secrets.PAT}}
        run:

          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

          echo "MODEL METRICS"
          cat metrics.txt